### ISSUE TITLE
Avaliação possível adaptação do modelo para trabalhar com multi-tenant

### ISSUE THREAD

**Issue by msoares94** [Throyer/springboot-api-crud#10]
Seria possível trabalhar na adaptação do modelo existente e adicionar o multi-tenant usando o MariaDB mesmo ou até mesmo o Postgres como por exemplo nesse repositório: https://github.com/amran-bd/Dynamic-Multi-Tenancy-Using-Java-Spring-Boot-Security-JWT-Rest-API-MySQL-Postgresql-full-example

**Comment by Throyer** [comment]
entendi, mas quando você diz adaptação ao que se refere?
As entidades presentes no projeto são somente entidades basicas já que a aplicação não tem nenhuma camada de negócios, porem se fosse evoluir pra uma aplicação maior e multi empresas (como um ERP por exemplo) isso envolveria outras entidades

sobre o uso de postgresql, é possivel mas acredito que ia precisar atualizar bastante coisa nas migrações já que foram feitas pensando no mariadb/mysql

uma coisa que eu não sei se foi o que você quis dizer com multi-tenant é sobre o uso de multiplos bancos de dados na mesma api, isso eu não sou muito fã pois considero um bad pattern

**Comment by msoares94** [comment]
Então @Throyer, adaptação me refiro ao projeto skeleton, trabalhar com a opção de multi-tenant somente, quando apontei o link para o outro repositório foi meio para ver a ideia pois o seu em questão de estrutura e recursos com o JWT, Refresh Token, Auditoria, etc é mais completo.

Quando me referi ao multi-tenant seria sim, nesse sentido de multiplos bancos, qual seria sua solução para ter um mesmo código fonte para tenants diferentes ?

Estou perguntando algumas coisas e até abrindo essas issue pois tem um projeto opensource feito em PHP (Laravel) que gostaria de fazer ele em Java, https://github.com/marcosoliveirasoares94/i-educar

Serve para escolas fazerem a gestão escolar e ele é opensource, logo, qualquer entidade de educação possa utilizar.

**Comment by Throyer** [comment]
Pra que seu projeto atenda múltiplas instituições você não precisa de mais de um banco de dados, foi o que eu quis dizer.

Esse problema você resolve na modelagem dependendo das suas regras de negocio

**Comment by msoares94** [comment]
Entendi @Throyer, obrigado!
