### ISSUE TITLE
Upgrade do Java

### ISSUE THREAD

**Issue by msoares94** [Throyer/springboot-api-crud#9]
Poderia aplicar a atualização do Java no projeto saindo do 16 no-lts e indo par ao 17 LTS

**Comment by Throyer** [comment]
@marcosoliveirasoares94 esse projeto serve mais como uma base do que uma aplicação real pronta pra produção, e por isso estava no java 16 já que eu queria experimentar algumas das features novas (originalmente ele era java 11)

o lançamento do LTS 17 é muito recente por isso que não subi a versão ainda

**Comment by msoares94** [comment]
Entendi @Throyer, só abri a issue pq lembrei que tinha a versão 17 LTS não quero atrapalhar seu projeto.

**Comment by Throyer** [comment]
tranquilo sem problemas, mas eu pretendo atualizar pro 17 sim. É que acabou de sair e eu nem vi ainda quais features que entraram

**Comment by Throyer** [comment]
@marcosoliveirasoares94 Boa noite amigo, recentemente fiz um monte de atualizações no projeto

agora existe uma parte "web app" também demonstrando uma sessão via cookie, mas a parte que era API anteriormente continua de pé também

também atualizei finalmente pra um jdk LTS haha

agora o projeto ta rodando no java 17  😁

**Comment by msoares94** [comment]
Olá @Throyer, obrigado por informar.

Irei dar uma olhada nas atualizações.
